name: elemental
description: A Flutter periodic table app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluid_bottom_nav_bar: ^1.3.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  dio: ^4.0.0
  lottie: ^1.0.1
  random_color: ^1.0.5
  flutter_cube: ^0.1.1
  url_launcher: ^6.0.6
  progress_indicator: ^0.2.0
  liquid_progress_indicator: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/Models/
